agent_class: hf
parameters:
    name: OpenOrca-Platypus2-13B
    model_name: Open-Orca/OpenOrca-Platypus2-13B
    prompt_name: OpenOrca-Platypus

    batch_size: 4

    # you can modify those generation config below
    do_sample: True
    temperature: 1
    top_p: 0.9
    max_new_tokens: 64
    min_new_tokens: 4