agent_class: hf
parameters:
    name: wizard-13b-v1.2
    model_name: WizardLM/WizardLM-13B-V1.2
    prompt_name: wizard

    batch_size: 32

    # you can modify those generation config below
    do_sample: True
    temperature: 1
    top_p: 0.9
    max_new_tokens: 64
    min_new_tokens: 4